<?php
// dashboard/export_orders_pdf.php - Admin: Export orders for a specific date to PDF
require_once '../config.php';
requireAdmin();
require_once '../lib/fpdf/fpdf.php';

if (!isset($_GET['date'])) {
    die("Please specify a date.");
}

$date = $_GET['date'];
$db = getDB();

// Fetch orders for the given date
$stmt = $db->prepare("
    SELECT o.*, g.title as product_name, g.price 
    FROM product_orders o 
    LEFT JOIN gallery g ON g.id = o.product_id 
    WHERE DATE(o.created_at) = ? 
    ORDER BY o.created_at ASC
");
$stmt->bind_param('s', $date);
$stmt->execute();
$orders = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$db->close();

if (empty($orders)) {
    die("No orders found for this date ($date).");
}

class OrderPDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(26, 107, 255); // Ecomedge Blue
        $this->Cell(0, 10, 'ECOMEDGE - CUSTOMER ORDERS', 0, 1, 'C');
        $this->SetFont('Arial', '', 10);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(0, 5, 'Date: ' . date('d M Y', strtotime($_GET['date'])), 0, 1, 'C');
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . ' | Generated by Ecomedge Management System', 0, 0, 'C');
    }
}

$pdf = new OrderPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 10);

foreach ($orders as $i => $o) {
    // Order Header
    $pdf->SetFillColor(248, 250, 255);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->SetTextColor(15, 23, 42);
    $pdf->Cell(0, 10, ' ORDER #' . $o['id'] . ' - ' . date('h:i A', strtotime($o['created_at'])), 1, 1, 'L', true);
    
    // Content
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(51, 65, 85);
    
    // MultiCell for details
    $details = "Product: " . ($o['product_name'] ?? 'Deleted') . " (Rs. " . ($o['price'] ?? '0') . ")\n" .
               "Customer: " . $o['customer_name'] . " | Phone: " . $o['phone'] . "\n" .
               "Address: " . $o['address'] . ", " . $o['city'] . "\n" .
               "House: " . ($o['house_no'] ?: 'N/A') . " | Street: " . ($o['street_no'] ?: 'N/A');
    
    $pdf->MultiCell(0, 7, $details, 1, 'L');
    $pdf->Ln(5);
    
    // Check for page break
    if ($pdf->GetY() > 250) {
        $pdf->AddPage();
    }
}

$pdf->Output('D', 'Ecomedge_Orders_' . $date . '.pdf');
?>
